version: '3.8'

services:
#  db:
#      container_name: msa_db
#      image: postgres:14
#      env_file:
#        - .env
#      environment:
#        POSTGRES_USER: ${DATABASE_USER?Variable not set}
#        POSTGRES_PASSWORD: ${DATABASE_PASSWORD?Variable not set}
#        POSTGRES_DB: ${DATABASE_DB?Variable not set}
#      ports:
#        - "6543:5432"
#      volumes:
#        - dbdata:/var/lib/postgresql/data
  app:
    container_name: msa_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "sh -c 'uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    #command: "sh -c 'alembic upgrade head && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - .:/app
    env_file:
      - .env
volumes:
  dbdata:
